version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: carbon_management_db
    environment:
      POSTGRES_DB: carbon_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - carbon_network

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: carbon_management_api
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: postgresql://postgres:password@postgres:5432/carbon_management
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      JWT_EXPIRES_IN: 7d
      CORS_ORIGIN: http://localhost:3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - carbon_network
    volumes:
      - ../src:/app/src
      - ../package.json:/app/package.json
      - ../tsconfig.json:/app/tsconfig.json

volumes:
  postgres_data:

networks:
  carbon_network:
    driver: bridge 